$ErrorActionPreference = "Stop"

# Step 04: Generate .env from provisioned resources and optionally bootstrap app assets.
# This script writes API key fallback values so the lab can run without additional RBAC setup.

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptDir "../..")
. "$scriptDir/00-variables.ps1"

$subscriptionId = az account show --query id -o tsv

$openaiEndpoint = az cognitiveservices account show --name $env:AZ_OPENAI_ACCOUNT_NAME --resource-group $env:AZ_RESOURCE_GROUP --query properties.endpoint -o tsv
$openaiKey = az cognitiveservices account keys list --name $env:AZ_OPENAI_ACCOUNT_NAME --resource-group $env:AZ_RESOURCE_GROUP --query key1 -o tsv

$cuEndpoint = az cognitiveservices account show --name $env:AZ_AISERVICES_ACCOUNT_NAME --resource-group $env:AZ_RESOURCE_GROUP --query properties.endpoint -o tsv
$cuKey = az cognitiveservices account keys list --name $env:AZ_AISERVICES_ACCOUNT_NAME --resource-group $env:AZ_RESOURCE_GROUP --query key1 -o tsv

$searchEndpoint = "https://$($env:AZ_SEARCH_SERVICE_NAME).search.windows.net"
$searchKey = az search admin-key show --service-name $env:AZ_SEARCH_SERVICE_NAME --resource-group $env:AZ_RESOURCE_GROUP --query primaryKey -o tsv

$storageConnectionString = az storage account show-connection-string --name $env:AZ_STORAGE_ACCOUNT_NAME --resource-group $env:AZ_RESOURCE_GROUP --query connectionString -o tsv

$envFilePath = Join-Path $repoRoot ".env"

@"
# Auto-generated by scripts/powershell/04-generate-env-and-bootstrap.ps1

AZURE_SUBSCRIPTION_ID=$subscriptionId
AZURE_RESOURCE_GROUP=$($env:AZ_RESOURCE_GROUP)

AZURE_AI_PROJECT_NAME=$($env:AZ_AISERVICES_ACCOUNT_NAME)
AZURE_AI_PROJECT_ENDPOINT=$cuEndpoint

AZURE_OPENAI_ENDPOINT=$openaiEndpoint
AZURE_OPENAI_DEPLOYMENT=$($env:AZ_OPENAI_DEPLOYMENT_NAME)
AZURE_OPENAI_API_VERSION=2024-12-01-preview

AZURE_SEARCH_ENDPOINT=$searchEndpoint
AZURE_SEARCH_INDEX_NAME=doc-review-index

AZURE_STORAGE_ACCOUNT_NAME=$($env:AZ_STORAGE_ACCOUNT_NAME)
AZURE_STORAGE_CONTAINER_NAME=$($env:AZ_STORAGE_CONTAINER_NAME)

AZURE_CU_ENDPOINT=$cuEndpoint
AZURE_CU_ANALYZER_ID=doc-review-analyzer

# API key fallback values for local workshop reliability.
AZURE_OPENAI_API_KEY=$openaiKey
AZURE_SEARCH_API_KEY=$searchKey
AZURE_CU_API_KEY=$cuKey
AZURE_STORAGE_CONNECTION_STRING=$storageConnectionString

APP_NAME=$($env:APP_NAME)
APP_VERSION=$($env:APP_VERSION)
"@ | Set-Content -Path $envFilePath -Encoding UTF8

Write-Host "Generated $envFilePath"

# Optional bootstrap: create search index and content understanding analyzer.
$pythonExists = Get-Command python -ErrorAction SilentlyContinue
if ($pythonExists) {
    Write-Host "Running optional bootstrap scripts..."
    Push-Location $repoRoot
    try {
        python scripts/create_search_index.py
        python scripts/create_cu_analyzer.py
    }
    catch {
        Write-Warning "One or more bootstrap scripts failed."
        Write-Warning "Check output above, then rerun manually after installing dependencies: pip install -r requirements.txt"
    }
    finally {
        Pop-Location
    }
}
else {
    Write-Warning "Python not found. Skipping bootstrap scripts."
}

Write-Host "Step 04 complete."
Write-Host "Next: uvicorn backend.main:app --reload --port 8000"
