#!/usr/bin/env bash
set -euo pipefail

# Step 04: Generate .env from provisioned resources and optionally bootstrap app assets.
# This script writes API key fallback values so the lab can run without additional RBAC setup.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
source "${SCRIPT_DIR}/00-variables.sh"

SUBSCRIPTION_ID="$(az account show --query id -o tsv)"

OPENAI_ENDPOINT="$(az cognitiveservices account show --name "${AZ_OPENAI_ACCOUNT_NAME}" --resource-group "${AZ_RESOURCE_GROUP}" --query properties.endpoint -o tsv)"
OPENAI_KEY="$(az cognitiveservices account keys list --name "${AZ_OPENAI_ACCOUNT_NAME}" --resource-group "${AZ_RESOURCE_GROUP}" --query key1 -o tsv)"

CU_ENDPOINT="$(az cognitiveservices account show --name "${AZ_AISERVICES_ACCOUNT_NAME}" --resource-group "${AZ_RESOURCE_GROUP}" --query properties.endpoint -o tsv)"
CU_KEY="$(az cognitiveservices account keys list --name "${AZ_AISERVICES_ACCOUNT_NAME}" --resource-group "${AZ_RESOURCE_GROUP}" --query key1 -o tsv)"

SEARCH_ENDPOINT="https://${AZ_SEARCH_SERVICE_NAME}.search.windows.net"
SEARCH_KEY="$(az search admin-key show --service-name "${AZ_SEARCH_SERVICE_NAME}" --resource-group "${AZ_RESOURCE_GROUP}" --query primaryKey -o tsv)"

STORAGE_CONNECTION_STRING="$(az storage account show-connection-string --name "${AZ_STORAGE_ACCOUNT_NAME}" --resource-group "${AZ_RESOURCE_GROUP}" --query connectionString -o tsv)"

cat > "${REPO_ROOT}/.env" <<EOF
# Auto-generated by scripts/bash/04-generate-env-and-bootstrap.sh

AZURE_SUBSCRIPTION_ID=${SUBSCRIPTION_ID}
AZURE_RESOURCE_GROUP=${AZ_RESOURCE_GROUP}

AZURE_AI_PROJECT_NAME=${AZ_AISERVICES_ACCOUNT_NAME}
AZURE_AI_PROJECT_ENDPOINT=${CU_ENDPOINT}

AZURE_OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
AZURE_OPENAI_DEPLOYMENT=${AZ_OPENAI_DEPLOYMENT_NAME}
AZURE_OPENAI_API_VERSION=2024-12-01-preview

AZURE_SEARCH_ENDPOINT=${SEARCH_ENDPOINT}
AZURE_SEARCH_INDEX_NAME=doc-review-index

AZURE_STORAGE_ACCOUNT_NAME=${AZ_STORAGE_ACCOUNT_NAME}
AZURE_STORAGE_CONTAINER_NAME=${AZ_STORAGE_CONTAINER_NAME}

AZURE_CU_ENDPOINT=${CU_ENDPOINT}
AZURE_CU_ANALYZER_ID=doc-review-analyzer

# API key fallback values for local workshop reliability.
AZURE_OPENAI_API_KEY=${OPENAI_KEY}
AZURE_SEARCH_API_KEY=${SEARCH_KEY}
AZURE_CU_API_KEY=${CU_KEY}
AZURE_STORAGE_CONNECTION_STRING=${STORAGE_CONNECTION_STRING}

APP_NAME=${APP_NAME}
APP_VERSION=${APP_VERSION}
EOF

echo "Generated ${REPO_ROOT}/.env"

# Optional bootstrap: create search index and content understanding analyzer.
if command -v python >/dev/null 2>&1; then
  echo "Running optional bootstrap scripts..."
  set +e
  (cd "${REPO_ROOT}" && python scripts/create_search_index.py)
  SEARCH_BOOTSTRAP_EXIT=$?
  (cd "${REPO_ROOT}" && python scripts/create_cu_analyzer.py)
  CU_BOOTSTRAP_EXIT=$?
  set -e

  if [[ ${SEARCH_BOOTSTRAP_EXIT} -ne 0 || ${CU_BOOTSTRAP_EXIT} -ne 0 ]]; then
    echo "WARNING: One or more bootstrap scripts failed."
    echo "Check output above, then rerun manually after installing dependencies: pip install -r requirements.txt"
  fi
else
  echo "Python not found. Skipping bootstrap scripts."
fi

echo "Step 04 complete."
echo "Next: uvicorn backend.main:app --reload --port 8000"
